version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'monthly'
