services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    deploy:
      resources:
        limits:
          memory: 2g
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "9200:9200"
    networks:
      - cheese_network

  elasticsearch_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch_test
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    deploy:
      resources:
        limits:
          memory: 2g
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "9201:9200"
    networks:
      - cheese_network

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    networks:
      - cheese_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh

  postgres_test:
    image: pgvector/pgvector:pg16
    container_name: postgres_test
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"
    networks:
      - cheese_network
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh

  # Valkey is a Redis-compatible key-value store
  valkey:
    image: valkey/valkey:8.0.2
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - cheese_network
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  valkey_test:
    image: valkey/valkey:8.0.2
    container_name: valkey_test
    ports:
      - "6380:6379"
    networks:
      - cheese_network
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  cheese_legacy:
    image: ghcr.io/sageseekersociety/cheese-backend:dev
    container_name: cheese_legacy
    ports:
      - "7777:7777"
    environment:
      - TZ=Asia/Shanghai
      - APP_NAME=Cheese
      - PORT=7777
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - FLYWAY_BASELINE_VERSION=20250328220000
      - PRISMA_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public&connection_limit=16
      - ELASTICSEARCH_NODE=http://elasticsearch:9200/
      - ELASTICSEARCH_AUTH_USERNAME=elastic
      - ELASTICSEARCH_AUTH_PASSWORD=elastic
      - FILE_UPLOAD_PATH=/app/uploads
      - DEFAULT_AVATAR_NAME=default.jpg
      - REDIS_HOST=valkey
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - WEB_AUTHN_RP_NAME=Cheese Community
    env_file:
      - .env
    volumes:
      - cheese_legacy_uploads:/app/uploads
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    networks:
      - cheese_network

  cheese_legacy_test:
    image: ghcr.io/sageseekersociety/cheese-backend:dev
    container_name: cheese_legacy_test
    ports:
      - "7779:7777"
    environment:
      - TZ=Asia/Shanghai
      - APP_NAME=Cheese
      - PORT=7777
      - POSTGRES_HOST=postgres_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - FLYWAY_BASELINE_VERSION=20250328220000
      - JWT_SECRET=test-secret
      - PRISMA_DATABASE_URL=postgresql://postgres:postgres@postgres_test:5432/postgres?schema=public&connection_limit=16
      - ELASTICSEARCH_NODE=http://elasticsearch_test:9200/
      - ELASTICSEARCH_AUTH_USERNAME=elastic
      - ELASTICSEARCH_AUTH_PASSWORD=elastic
      - FILE_UPLOAD_PATH=/app/uploads
      - DEFAULT_AVATAR_NAME=default.jpg
      - REDIS_HOST=valkey_test
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - WEB_AUTHN_RP_NAME=Cheese Community
    env_file:
      - .env
    volumes:
      - cheese_legacy_uploads_test:/app/uploads
    depends_on:
      elasticsearch_test:
        condition: service_healthy
      postgres_test:
        condition: service_healthy
      valkey_test:
        condition: service_healthy
    networks:
      - cheese_network

networks:
  cheese_network:
    name: cheese_network

volumes:
  postgres_data:
  postgres_data_test:
  cheese_legacy_uploads:
  cheese_legacy_uploads_test:
