/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package org.rucca.cheese.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import kotlin.collections.List
import org.rucca.cheese.model.KnowledgeGet200ResponseDTO
import org.rucca.cheese.model.KnowledgePost200ResponseDTO
import org.rucca.cheese.model.KnowledgePostRequestDTO
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface KnowledgeApi {

    @Operation(
        tags = ["default"],
        summary = "List Knowledge Items",
        operationId = "knowledgeGet",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = KnowledgeGet200ResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/knowledge"],
        produces = ["application/json"],
    )
    fun knowledgeGet(
        @Parameter(description = "项目ID列表 (可选)")
        @Valid
        @RequestParam(value = "project_ids", required = false)
        projectIds: kotlin.collections.List<kotlin.Long>?,
        @Parameter(description = "类型 (可选)")
        @Valid
        @RequestParam(value = "type", required = false)
        type: kotlin.String?,
        @Parameter(description = "标签列表 (可选)")
        @Valid
        @RequestParam(value = "labels", required = false)
        labels: kotlin.collections.List<kotlin.String>?,
        @Parameter(description = "搜索关键词 (可选)")
        @Valid
        @RequestParam(value = "query", required = false)
        query: kotlin.String?,
        @Parameter(description = "起始ID")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "每页数量 (默认20)", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<KnowledgeGet200ResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["default"],
        summary = "Create Knowledge Item",
        operationId = "knowledgePost",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = KnowledgePost200ResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/knowledge"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun knowledgePost(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        knowledgePostRequestDTO: KnowledgePostRequestDTO
    ): ResponseEntity<KnowledgePost200ResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
