/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package org.rucca.cheese.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.rucca.cheese.model.CreateProject200ResponseDTO
import org.rucca.cheese.model.CreateProjectRequestDTO
import org.rucca.cheese.model.GetProjects200ResponseDTO
import org.rucca.cheese.model.ProjectsProjectIdDiscussionsDiscussionIdReactionsPost200ResponseDTO
import org.rucca.cheese.model.ProjectsProjectIdDiscussionsDiscussionIdReactionsPostRequestDTO
import org.rucca.cheese.model.ProjectsProjectIdDiscussionsGet200ResponseDTO
import org.rucca.cheese.model.ProjectsProjectIdDiscussionsGetProjectFilterParameterDTO
import org.rucca.cheese.model.ProjectsProjectIdDiscussionsPost200ResponseDTO
import org.rucca.cheese.model.ProjectsProjectIdDiscussionsPostRequestDTO
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface ProjectsApi {

    @Operation(
        tags = ["default"],
        summary = "Create Project",
        operationId = "createProject",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = CreateProject200ResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/projects"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createProject(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createProjectRequestDTO: CreateProjectRequestDTO
    ): ResponseEntity<CreateProject200ResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["default"],
        summary = "List Projects",
        operationId = "getProjects",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = GetProjects200ResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/projects"],
        produces = ["application/json"],
    )
    fun getProjects(
        @Parameter(description = "父项目ID (可选)")
        @Valid
        @RequestParam(value = "parent_id", required = false)
        parentId: kotlin.Long?,
        @Parameter(description = "负责人ID (可选)")
        @Valid
        @RequestParam(value = "leader_id", required = false)
        leaderId: kotlin.Long?,
        @Parameter(description = "成员ID (可选)")
        @Valid
        @RequestParam(value = "member_id", required = false)
        memberId: kotlin.Long?,
        @Parameter(description = "起始ID")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "每页数量 (默认20)", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<GetProjects200ResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["default"],
        summary = "React to Discussion",
        operationId = "projectsProjectIdDiscussionsDiscussionIdReactionsPost",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(
                                        implementation =
                                            ProjectsProjectIdDiscussionsDiscussionIdReactionsPost200ResponseDTO::class
                                    )
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/projects/{projectId}/discussions/{discussionId}/reactions"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun projectsProjectIdDiscussionsDiscussionIdReactionsPost(
        @Parameter(description = "项目ID", required = true)
        @PathVariable("projectId")
        projectId: kotlin.Long,
        @Parameter(description = "讨论ID", required = true)
        @PathVariable("discussionId")
        discussionId: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        projectsProjectIdDiscussionsDiscussionIdReactionsPostRequestDTO:
            ProjectsProjectIdDiscussionsDiscussionIdReactionsPostRequestDTO,
    ): ResponseEntity<ProjectsProjectIdDiscussionsDiscussionIdReactionsPost200ResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["default"],
        summary = "List Discussions",
        operationId = "projectsProjectIdDiscussionsGet",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(
                                        implementation =
                                            ProjectsProjectIdDiscussionsGet200ResponseDTO::class
                                    )
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/projects/{projectId}/discussions"],
        produces = ["application/json"],
    )
    fun projectsProjectIdDiscussionsGet(
        @Parameter(description = "项目ID", required = true)
        @PathVariable("projectId")
        projectId: kotlin.Long,
        @Parameter(description = "项目过滤器")
        @Valid
        projectFilter: ProjectsProjectIdDiscussionsGetProjectFilterParameterDTO?,
        @Parameter(description = "时间戳(毫秒)")
        @Valid
        @RequestParam(value = "before", required = false)
        before: kotlin.Long?,
        @Parameter(description = "起始ID")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "每页数量 (默认20)", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ProjectsProjectIdDiscussionsGet200ResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["default"],
        summary = "Create Discussion",
        operationId = "projectsProjectIdDiscussionsPost",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(
                                        implementation =
                                            ProjectsProjectIdDiscussionsPost200ResponseDTO::class
                                    )
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/projects/{projectId}/discussions"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun projectsProjectIdDiscussionsPost(
        @Parameter(description = "项目ID", required = true)
        @PathVariable("projectId")
        projectId: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        projectsProjectIdDiscussionsPostRequestDTO: ProjectsProjectIdDiscussionsPostRequestDTO,
    ): ResponseEntity<ProjectsProjectIdDiscussionsPost200ResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
