---------------------------------------------------------------------------
--                        DO NOT MODIFY THIS FILE                        --
--                                                                       --
-- The following content is generated by JPA according to entity classes --
---------------------------------------------------------------------------
CREATE
    TABLE
        public."user"(
            id INTEGER NOT NULL,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            deleted_at TIMESTAMP(6) WITH TIME ZONE,
            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            email text NOT NULL,
            hashed_password text,
            username text NOT NULL,
            PRIMARY KEY(id),
            CONSTRAINT IDX_78a916df40e02a9deb1c4b75ed UNIQUE(username),
            CONSTRAINT IDX_e12875dfb3b1d92d7d7c5377e2 UNIQUE(email)
        );

CREATE
    TABLE
        public.user_profile(
            avatar_id INTEGER NOT NULL,
            id INTEGER NOT NULL,
            user_id INTEGER NOT NULL UNIQUE,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            deleted_at TIMESTAMP(6) WITH TIME ZONE,
            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            intro text NOT NULL,
            nickname text NOT NULL,
            CONSTRAINT IDX_51cb79b5555effaf7d69ba1cff PRIMARY KEY(id)
        );

CREATE
    SEQUENCE ai_conversation_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE ai_message_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE attachment_id_seq
START WITH
    1 INCREMENT BY 1;

CREATE
    SEQUENCE discussion_reaction_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE discussion_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE knowledge_label_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE knowledge_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE material_bundle_id_seq
START WITH
    1 INCREMENT BY 1;

CREATE
    SEQUENCE material_id_seq
START WITH
    1 INCREMENT BY 1;

CREATE
    SEQUENCE notification_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE project_membership_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE project_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE reaction_type_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE space_admin_relation_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE space_categories_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE space_classification_topics_relation_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE space_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE space_user_rank_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE task_ai_advice_context_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE task_membership_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE task_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE task_submission_entry_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE task_submission_review_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE task_submission_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE task_topics_relation_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE team_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE team_user_relation_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE topic_id_seq
START WITH
    1 INCREMENT BY 1;

CREATE
    SEQUENCE user_ai_quota_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE user_id_seq
START WITH
    1 INCREMENT BY 1;

CREATE
    SEQUENCE user_profile_id_seq
START WITH
    1 INCREMENT BY 1;

CREATE
    SEQUENCE user_real_name_access_logs_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE user_real_name_identities_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE user_seu_consumption_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    TABLE
        ai_conversation(
            context_id BIGINT,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            owner_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            conversation_id VARCHAR(255) NOT NULL UNIQUE,
            model_type TEXT DEFAULT 'standard' NOT NULL,
            module_type VARCHAR(255) NOT NULL,
            title VARCHAR(255),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        ai_message(
            seu_consumed NUMERIC(
                10,
                4
            ),
            tokens_used INTEGER,
            conversation_id BIGINT NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            parent_id BIGINT,
            reasoning_time_ms BIGINT,
            updated_at TIMESTAMP(6) NOT NULL,
            content TEXT NOT NULL,
            model_type TEXT DEFAULT 'standard' NOT NULL,
            reasoning_content TEXT,
            ROLE VARCHAR(255) NOT NULL,
            metadata JSONB,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        attachment(
            id INTEGER NOT NULL,
            TYPE VARCHAR(255) NOT NULL,
            meta jsonb NOT NULL,
            url text NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        avatar(
            id INTEGER DEFAULT nextval('avatar_id_seq') NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        discussion(
            sender_id INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            model_id BIGINT NOT NULL,
            parent_id BIGINT,
            updated_at TIMESTAMP(6) NOT NULL,
            model_type VARCHAR(255) NOT NULL CHECK(
                model_type IN(
                    'PROJECT',
                    'SPACE'
                )
            ),
            content JSONB NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        discussion_mentioned_users(
            discussion_id BIGINT NOT NULL,
            user_id BIGINT
        );

CREATE
    TABLE
        discussion_reaction(
            user_id INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            discussion_id BIGINT NOT NULL,
            id BIGINT NOT NULL,
            reaction_type_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            PRIMARY KEY(id),
            CONSTRAINT uk_discussion_reaction_user_type UNIQUE(
                discussion_id,
                user_id,
                reaction_type_id
            )
        );

CREATE
    TABLE
        encryption_keys(
            purpose SMALLINT NOT NULL CHECK(
                purpose BETWEEN 0 AND 1
            ),
            created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            related_entity_id BIGINT,
            id VARCHAR(255) NOT NULL,
            key_value VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        knowledge(
            "created_by_id" INTEGER NOT NULL,
            material_id INTEGER,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            discussion_id BIGINT,
            id BIGINT NOT NULL,
            project_id BIGINT,
            team_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            description text NOT NULL,
            name VARCHAR(255) NOT NULL,
            source_type VARCHAR(255) NOT NULL CHECK(
                source_type IN(
                    'MANUAL',
                    'FROM_DISCUSSION'
                )
            ),
            TYPE VARCHAR(255) NOT NULL CHECK(
                TYPE IN(
                    'MATERIAL',
                    'LINK',
                    'TEXT',
                    'CODE'
                )
            ),
            content jsonb NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        knowledge_knowledge_labels(
            knowledge_id BIGINT NOT NULL,
            knowledge_labels_id BIGINT NOT NULL UNIQUE
        );

CREATE
    TABLE
        knowledge_label(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            knowledge_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            label VARCHAR(50) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        material(
            download_count INTEGER DEFAULT 0 NOT NULL,
            expires INTEGER,
            id INTEGER NOT NULL,
            uploader_id INTEGER NOT NULL,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            TYPE VARCHAR(255) NOT NULL,
            meta jsonb NOT NULL,
            name text NOT NULL,
            url text NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        material_bundle(
            comments_count INTEGER DEFAULT 0 NOT NULL,
            creator_id INTEGER NOT NULL,
            id INTEGER NOT NULL,
            my_rating FLOAT(53),
            rating FLOAT(53) DEFAULT 0 NOT NULL,
            rating_count INTEGER DEFAULT 0 NOT NULL,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            content text NOT NULL,
            title text NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        materialbundles_relation(
            bundle_id INTEGER NOT NULL,
            material_id INTEGER NOT NULL,
            PRIMARY KEY(
                bundle_id,
                material_id
            )
        );

CREATE
    TABLE
        notification(
            READ BOOLEAN NOT NULL,
            receiver_id INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            TYPE VARCHAR(255) NOT NULL CHECK(
                TYPE IN(
                    'MENTION',
                    'REPLY',
                    'REACTION',
                    'PROJECT_INVITE',
                    'DEADLINE_REMIND'
                )
            ),
            content JSONB,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        project(
            archived BOOLEAN DEFAULT FALSE NOT NULL,
            color_code VARCHAR(7) NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            end_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            external_task_id BIGINT,
            id BIGINT NOT NULL,
            leader_id BIGINT NOT NULL,
            parent_id BIGINT,
            start_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
            team_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            description text NOT NULL,
            github_repo VARCHAR(255),
            name VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        project_membership(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            project_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            user_id BIGINT NOT NULL,
            notes text,
            ROLE VARCHAR(255) NOT NULL CHECK(
                ROLE IN(
                    'LEADER',
                    'MEMBER',
                    'EXTERNAL'
                )
            ),
            PRIMARY KEY(id),
            UNIQUE(
                project_id,
                user_id
            )
        );

CREATE
    TABLE
        reaction_type(
            display_order INTEGER NOT NULL,
            is_active BOOLEAN NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            code VARCHAR(32) NOT NULL,
            name VARCHAR(64) NOT NULL,
            description VARCHAR(255),
            PRIMARY KEY(id),
            CONSTRAINT idx_reaction_type_code UNIQUE(code)
        );

CREATE
    TABLE
        SPACE(
            avatar_id INTEGER NOT NULL,
            enable_rank BOOLEAN NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            default_category_id BIGINT,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            announcements TEXT NOT NULL,
            description TEXT NOT NULL,
            intro VARCHAR(255) NOT NULL,
            name VARCHAR(255) NOT NULL,
            task_templates TEXT NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        space_categories(
            display_order INT DEFAULT 0 NOT NULL,
            archived_at TIMESTAMP(6) WITH TIME ZONE,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            space_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            description TEXT,
            name VARCHAR(255) NOT NULL,
            PRIMARY KEY(id),
            UNIQUE(
                space_id,
                name
            )
        );

CREATE
    TABLE
        space_admin_relation(
            ROLE SMALLINT NOT NULL CHECK(
                ROLE BETWEEN 0 AND 1
            ),
            "user_id" INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            space_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        space_classification_topics_relation(
            topic_id INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            space_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        space_user_rank(
            RANK INTEGER NOT NULL,
            "user_id" INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            space_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        task(
            approved SMALLINT NOT NULL CHECK(
                approved BETWEEN 0 AND 2
            ),
            creator_id INTEGER NOT NULL,
            editable BOOLEAN NOT NULL,
            max_team_size INTEGER,
            min_team_size INTEGER,
            participant_limit INTEGER,
            RANK INTEGER,
            require_real_name BOOLEAN DEFAULT FALSE NOT NULL,
            resubmittable BOOLEAN NOT NULL,
            submitter_type SMALLINT NOT NULL CHECK(
                submitter_type BETWEEN 0 AND 1
            ),
            category_id BIGINT NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deadline TIMESTAMP(6),
            default_deadline BIGINT NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            space_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            description TEXT NOT NULL,
            intro VARCHAR(255) NOT NULL,
            name VARCHAR(255) NOT NULL,
            reject_reason VARCHAR(255),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        task_ai_advice(
            created_at TIMESTAMP(6) NOT NULL,
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            task_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            model_hash VARCHAR(64) NOT NULL,
            knowledge_fields TEXT,
            learning_paths TEXT,
            methodology TEXT,
            raw_response TEXT,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'PENDING',
                    'PROCESSING',
                    'COMPLETED',
                    'FAILED'
                )
            ),
            team_tips TEXT,
            topic_summary TEXT,
            PRIMARY KEY(id),
            UNIQUE(
                task_id,
                model_hash
            )
        );

CREATE
    TABLE
        task_ai_advice_context(
            section_index INTEGER,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            task_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            SECTION VARCHAR(255),
            PRIMARY KEY(id),
            CONSTRAINT uk_task_section_index UNIQUE(
                task_id,
                SECTION,
                section_index
            )
        );

CREATE
    TABLE
        task_membership_team_members(
            encrypted BOOLEAN DEFAULT FALSE,
            member_id BIGINT NOT NULL,
            task_membership_id BIGINT NOT NULL,
            class_name VARCHAR(255),
            grade VARCHAR(255),
            major VARCHAR(255),
            real_name VARCHAR(255),
            student_id VARCHAR(255)
        );

CREATE
    TABLE
        task_submission_schema(
            INDEX INTEGER NOT NULL,
            TYPE SMALLINT NOT NULL CHECK(
                TYPE BETWEEN 0 AND 1
            ),
            task_id BIGINT NOT NULL,
            description VARCHAR(255) NOT NULL
        );

CREATE
    TABLE
        task_membership(
            approved SMALLINT NOT NULL CHECK(
                approved BETWEEN 0 AND 2
            ),
            encrypted BOOLEAN DEFAULT FALSE,
            is_team BOOLEAN NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deadline TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            member_id BIGINT NOT NULL,
            task_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            apply_reason VARCHAR(255) NOT NULL,
            class_name VARCHAR(255),
            email VARCHAR(255) NOT NULL,
            encryption_key_id VARCHAR(255),
            grade VARCHAR(255),
            major VARCHAR(255),
            personal_advantage VARCHAR(255) NOT NULL,
            phone VARCHAR(255) NOT NULL,
            real_name VARCHAR(255),
            remark VARCHAR(255) NOT NULL,
            student_id VARCHAR(255),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        task_submission(
            submitter_id INTEGER NOT NULL,
            version INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            membership_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        task_submission_entry(
            content_attachment_id INTEGER,
            INDEX INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            task_submission_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            content_text VARCHAR(255),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        task_submission_review(
            accepted BOOLEAN NOT NULL,
            score INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            submission_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            comment VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        task_topics_relation(
            topic_id INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            task_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        team(
            avatar_id INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            description TEXT NOT NULL,
            intro VARCHAR(255) NOT NULL,
            name VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        team_user_relation(
            ROLE SMALLINT NOT NULL CHECK(
                ROLE BETWEEN 0 AND 2
            ),
            "user_id" INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            team_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        topic(
            created_by_id INTEGER NOT NULL,
            id INTEGER NOT NULL,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            deleted_at TIMESTAMP(6) WITH TIME ZONE,
            name text NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        user_ai_quota(
            daily_seu_quota NUMERIC(
                10,
                4
            ),
            remaining_seu NUMERIC(
                10,
                4
            ),
            total_seu_consumed NUMERIC(
                10,
                4
            ),
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            last_reset_time TIMESTAMP(6),
            updated_at TIMESTAMP(6) NOT NULL,
            user_id BIGINT,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        user_real_name_access_logs(
            accessor_id BIGINT NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            module_entity_id BIGINT,
            target_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            access_reason VARCHAR(255) NOT NULL,
            access_type VARCHAR(255) NOT NULL CHECK(
                access_type IN(
                    'VIEW',
                    'EXPORT'
                )
            ),
            ip_address VARCHAR(255) NOT NULL,
            module_type VARCHAR(255) CHECK(
                module_type IN('TASK')
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        user_real_name_identities(
            encrypted BOOLEAN DEFAULT FALSE NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            user_id BIGINT NOT NULL,
            class_name VARCHAR(255) NOT NULL,
            encryption_key_id VARCHAR(255) NOT NULL,
            grade VARCHAR(255) NOT NULL,
            major VARCHAR(255) NOT NULL,
            real_name VARCHAR(255) NOT NULL,
            student_id VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        user_role(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            user_id BIGINT NOT NULL,
            ROLE VARCHAR(255) NOT NULL CHECK(
                ROLE IN(
                    'SUPER_ADMIN',
                    'ADMIN',
                    'MODERATOR',
                    'USER'
                )
            ),
            PRIMARY KEY(id),
            UNIQUE(
                user_id,
                ROLE
            )
        );

CREATE
    TABLE
        user_seu_consumption(
            is_cached BOOLEAN,
            seu_consumed NUMERIC(
                10,
                4
            ),
            tokens_used INTEGER,
            cache_expire_at TIMESTAMP(6),
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            user_id BIGINT,
            cache_key VARCHAR(255),
            request_id VARCHAR(255),
            resource_type VARCHAR(255) CHECK(
                resource_type IN(
                    'LIGHTWEIGHT',
                    'STANDARD',
                    'ADVANCED'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    INDEX IDXiuy7mmgy0obas3bfqu1j519bc ON
    discussion(
        model_type,
        model_id
    );

CREATE
    INDEX IDXkhxb42bgml7ds4m1mn25ulgpj ON
    discussion(sender_id);

CREATE
    INDEX idx_reaction_discussion_type ON
    discussion_reaction(
        discussion_id,
        reaction_type_id
    );

CREATE
    INDEX idx_reaction_discussion_user ON
    discussion_reaction(
        discussion_id,
        user_id
    );

CREATE
    INDEX IDXaj3gr2rwnv7uamdf03p78372m ON
    knowledge(name);

CREATE
    INDEX IDXlk5f1tf6v3vslj8o1rfqwgcwi ON
    knowledge(team_id);

CREATE
    INDEX IDXjabwimmbvt40wl20fp0kaevp4 ON
    knowledge(source_type);

CREATE
    INDEX IDXk01yi4pk1orlwhihsorqhnwr8 ON
    knowledge(project_id);

CREATE
    INDEX IDXp6qd6pe6q2uaa78bypcy99k2k ON
    knowledge(discussion_id);

CREATE
    INDEX IDXiyfipycyf7afycfn9f8gkhcvf ON
    knowledge_label(knowledge_id);

CREATE
    INDEX IDX2lm01yrx3fukjj9a89v0hpr2 ON
    knowledge_label(label);

CREATE
    INDEX IDX3k75vvu7mevyvvb5may5lj8k7 ON
    project(name);

CREATE
    INDEX IDXrl2bt06yn51j9nbk2d0tjituy ON
    project(team_id);

CREATE
    INDEX IDXif1pq04iwqmv1xrsf892htked ON
    project(leader_id);

CREATE
    INDEX IDXkycbyj306lg659w6g2ceuqpnu ON
    project(parent_id);

CREATE
    INDEX IDX95fxueh91d9uobhmly6smcdtw ON
    project_membership(project_id);

CREATE
    INDEX IDXc0ggmiab5m1chu88hitikohha ON
    project_membership(user_id);

CREATE
    INDEX IDXobr8vksep0or878byk2kohpty ON
    project_membership(ROLE);

CREATE
    INDEX IDXmllyu96n9vj606vm9w0gp3obx ON
    SPACE(name);

CREATE
    INDEX idx_spacecategories_archived ON
    space_categories(archived_at);

CREATE
    INDEX IDXfmekoev1y1edqr9achyy8jp3b ON
    space_admin_relation(space_id);

CREATE
    INDEX IDX9kayuwile36o13jipo63b10sb ON
    space_admin_relation(user_id);

CREATE
    INDEX IDXo1hn4jgjd2kpue9yt0ptyj2jp ON
    space_classification_topics_relation(space_id);

CREATE
    INDEX IDXby2rktc4t1x2cvvlps3gx5pg3 ON
    space_classification_topics_relation(topic_id);

CREATE
    INDEX IDX5se9sb4u9yywkp49gnim8s85n ON
    space_user_rank(space_id);

CREATE
    INDEX IDX4poyg61j8nhdhsryne7s8snmr ON
    space_user_rank(user_id);

CREATE
    INDEX IDX70x5oq6omtraaie2fttiv25rd ON
    task_membership(task_id);

CREATE
    INDEX IDXh685vv2ufp7ohjnfw6hw231tv ON
    task_membership(member_id);

CREATE
    INDEX IDXglmpyfy44ju9tr2tm5h6j8u3t ON
    task_submission(membership_id);

CREATE
    INDEX IDXlac91yl30evfn8mq1kh91jyyg ON
    task_submission_entry(task_submission_id);

CREATE
    INDEX IDX3ctl72phv5d0yluddhpkxb1y4 ON
    task_submission_review(submission_id);

CREATE
    INDEX IDXka5lit0ursfthx3207eojpvn7 ON
    task_topics_relation(task_id);

CREATE
    INDEX IDXop6rbg45aknhvuqaakuonifao ON
    task_topics_relation(topic_id);

CREATE
    INDEX IDXg2l9qqsoeuynt4r5ofdt1x2td ON
    team(name);

CREATE
    INDEX IDXd45hsmkordpydcytq25ahcnby ON
    team_user_relation(team_id);

CREATE
    INDEX IDXquiqutq8cnj700u982xlo8bsm ON
    team_user_relation(user_id);

CREATE
    INDEX IDXapcc8lxk2xnug8377fatvbn04 ON
    user_role(user_id);

ALTER TABLE
    IF EXISTS public.user_profile ADD CONSTRAINT FKo5dcemd97atrmjapi9x4s1j32 FOREIGN KEY(avatar_id) REFERENCES avatar;

ALTER TABLE
    IF EXISTS public.user_profile ADD CONSTRAINT FKqcd5nmg7d7ement27tt9sf3bi FOREIGN KEY(user_id) REFERENCES public."user";

ALTER TABLE
    IF EXISTS ai_message ADD CONSTRAINT FKsaxwtwysovynl73cqwffe1fbn FOREIGN KEY(conversation_id) REFERENCES ai_conversation;

ALTER TABLE
    IF EXISTS discussion ADD CONSTRAINT FKgs1dxhfnb68rh344y4f34fwqa FOREIGN KEY(parent_id) REFERENCES discussion;

ALTER TABLE
    IF EXISTS discussion ADD CONSTRAINT FK7wmfmeiq6a9y5ygdi1obp01r FOREIGN KEY(sender_id) REFERENCES public."user";

ALTER TABLE
    IF EXISTS discussion_mentioned_users ADD CONSTRAINT FKg7pxkxyxyxq2g2qttjeyph6ra FOREIGN KEY(discussion_id) REFERENCES discussion;

ALTER TABLE
    IF EXISTS discussion_reaction ADD CONSTRAINT FKawpinudxl9749buwtradij9p6 FOREIGN KEY(discussion_id) REFERENCES discussion;

ALTER TABLE
    IF EXISTS discussion_reaction ADD CONSTRAINT FK9r8w78vm7sdf6iqkcl0pc9jqp FOREIGN KEY(reaction_type_id) REFERENCES reaction_type;

ALTER TABLE
    IF EXISTS discussion_reaction ADD CONSTRAINT FKjh9fs8xa2fuupaw2josqcjbfv FOREIGN KEY(user_id) REFERENCES public."user";

ALTER TABLE
    IF EXISTS knowledge ADD CONSTRAINT FKacal20h046lgv8bl4bkl2di1f FOREIGN KEY("created_by_id") REFERENCES public."user";

ALTER TABLE
    IF EXISTS knowledge ADD CONSTRAINT FKhniy1bsjjeoxbpfnlwydlgxtk FOREIGN KEY(material_id) REFERENCES material;

ALTER TABLE
    IF EXISTS knowledge ADD CONSTRAINT FK1df46ccdrd9w7i5bf1urij4j2 FOREIGN KEY(discussion_id) REFERENCES discussion;

ALTER TABLE
    IF EXISTS knowledge ADD CONSTRAINT FKs854y5ajesie1jja4thskulsc FOREIGN KEY(team_id) REFERENCES team;

ALTER TABLE
    IF EXISTS knowledge_knowledge_labels ADD CONSTRAINT FKd9dp2f3c65b8d2gdc9oeql6ja FOREIGN KEY(knowledge_labels_id) REFERENCES knowledge_label;

ALTER TABLE
    IF EXISTS knowledge_knowledge_labels ADD CONSTRAINT FKbdxbbpetfqn7y3cuq50tgcuoq FOREIGN KEY(knowledge_id) REFERENCES knowledge;

ALTER TABLE
    IF EXISTS knowledge_label ADD CONSTRAINT FK43k38w4y2j691mb6nhyijhq96 FOREIGN KEY(knowledge_id) REFERENCES knowledge;

ALTER TABLE
    IF EXISTS material ADD CONSTRAINT FK21nqwvdonsvsnp7r3d9uo17bo FOREIGN KEY(uploader_id) REFERENCES public."user" ON
    DELETE
        RESTRICT;

ALTER TABLE
    IF EXISTS material_bundle ADD CONSTRAINT FKl3r75ka0qydpitvbtayq7grsi FOREIGN KEY(creator_id) REFERENCES public."user" ON
    DELETE
        RESTRICT;

ALTER TABLE
    IF EXISTS materialbundles_relation ADD CONSTRAINT FK5fkpr8538ghw2wfjten9hergi FOREIGN KEY(bundle_id) REFERENCES material_bundle ON
    DELETE
        CASCADE;

ALTER TABLE
    IF EXISTS materialbundles_relation ADD CONSTRAINT FK62blmnwrqevg0whwwv5231b5g FOREIGN KEY(material_id) REFERENCES material ON
    DELETE
        RESTRICT;

ALTER TABLE
    IF EXISTS notification ADD CONSTRAINT FKs951ba5cqr6ibbu6w295b3ljg FOREIGN KEY(receiver_id) REFERENCES public."user";

ALTER TABLE
    IF EXISTS project ADD CONSTRAINT FKt0just6g3205u402vn88i0fhy FOREIGN KEY(parent_id) REFERENCES project;

ALTER TABLE
    IF EXISTS project_membership ADD CONSTRAINT FK6nerxrll628ug1mvgpt2spgpk FOREIGN KEY(project_id) REFERENCES project;

ALTER TABLE
    IF EXISTS SPACE ADD CONSTRAINT FK77tn26hq1ml6ri82fp970we8n FOREIGN KEY(avatar_id) REFERENCES avatar;

ALTER TABLE
    IF EXISTS SPACE ADD CONSTRAINT FKfumv58c5xoatfj5qa9cw6grgy FOREIGN KEY(default_category_id) REFERENCES space_categories;

ALTER TABLE
    IF EXISTS space_categories ADD CONSTRAINT FKtk9fc6aqpb9hr1yg4rk284a2i FOREIGN KEY(space_id) REFERENCES SPACE;

ALTER TABLE
    IF EXISTS space_admin_relation ADD CONSTRAINT FKhkpyunhmsubl1gvahyk9e9lff FOREIGN KEY(space_id) REFERENCES SPACE;

ALTER TABLE
    IF EXISTS space_admin_relation ADD CONSTRAINT FKd3x1m946orup61b4f4wu6h2xn FOREIGN KEY("user_id") REFERENCES public."user";

ALTER TABLE
    IF EXISTS space_classification_topics_relation ADD CONSTRAINT FKtfux67slxlrbd7975e7066vq FOREIGN KEY(space_id) REFERENCES SPACE;

ALTER TABLE
    IF EXISTS space_classification_topics_relation ADD CONSTRAINT FKpvs648o6f6bdvjsa27dd2pdp1 FOREIGN KEY(topic_id) REFERENCES topic;

ALTER TABLE
    IF EXISTS space_user_rank ADD CONSTRAINT FKh0k0jxvhnph0eoc5gw7652hdy FOREIGN KEY(space_id) REFERENCES SPACE;

ALTER TABLE
    IF EXISTS space_user_rank ADD CONSTRAINT FKiego7kcolpikn8o93o3qdjt3p FOREIGN KEY("user_id") REFERENCES public."user";

ALTER TABLE
    IF EXISTS task ADD CONSTRAINT FKm8oxgq962olauqi7d4s0cufoj FOREIGN KEY(category_id) REFERENCES space_categories;

ALTER TABLE
    IF EXISTS task ADD CONSTRAINT FKgbm6entex11ihw1lb57wb1vgt FOREIGN KEY(creator_id) REFERENCES public."user";

ALTER TABLE
    IF EXISTS task ADD CONSTRAINT FKe6m3e5625asfu59r4doayop1o FOREIGN KEY(space_id) REFERENCES SPACE;

ALTER TABLE
    IF EXISTS task_membership_team_members ADD CONSTRAINT FKqqe540ncjf6ylguc5r3mt51sm FOREIGN KEY(task_membership_id) REFERENCES task_membership;

ALTER TABLE
    IF EXISTS task_submission_schema ADD CONSTRAINT FKeipe4rx4f493n82xgon4padr5 FOREIGN KEY(task_id) REFERENCES task;

ALTER TABLE
    IF EXISTS task_membership ADD CONSTRAINT FK6jngswgv5k77n9pj70f18a49y FOREIGN KEY(task_id) REFERENCES task;

ALTER TABLE
    IF EXISTS task_submission ADD CONSTRAINT FK7p8ct6x90ypn5ubixkg9a5cf3 FOREIGN KEY(membership_id) REFERENCES task_membership;

ALTER TABLE
    IF EXISTS task_submission ADD CONSTRAINT FKgqx6epr8btfbjv5lneb6ayqu4 FOREIGN KEY(submitter_id) REFERENCES public."user";

ALTER TABLE
    IF EXISTS task_submission_entry ADD CONSTRAINT FK8d9mtcc0w6k35dfj8csp6hsos FOREIGN KEY(content_attachment_id) REFERENCES attachment;

ALTER TABLE
    IF EXISTS task_submission_entry ADD CONSTRAINT FK3rhnhj7id0krtih5rhveivmgc FOREIGN KEY(task_submission_id) REFERENCES task_submission;

ALTER TABLE
    IF EXISTS task_submission_review ADD CONSTRAINT FKba2fmo0mgjdlohcnpf97tvgvt FOREIGN KEY(submission_id) REFERENCES task_submission;

ALTER TABLE
    IF EXISTS task_topics_relation ADD CONSTRAINT FKjbxaijxjd045fy4ry2pxenrir FOREIGN KEY(task_id) REFERENCES task;

ALTER TABLE
    IF EXISTS task_topics_relation ADD CONSTRAINT FKd1esf4rvrn7eedttnfqs5dfw1 FOREIGN KEY(topic_id) REFERENCES topic;

ALTER TABLE
    IF EXISTS team ADD CONSTRAINT FKjv1k745e89swu3gj896pxcq3y FOREIGN KEY(avatar_id) REFERENCES avatar;

ALTER TABLE
    IF EXISTS team_user_relation ADD CONSTRAINT FKtf9y6q1stv6vpqtlclj1okjxs FOREIGN KEY(team_id) REFERENCES team;

ALTER TABLE
    IF EXISTS team_user_relation ADD CONSTRAINT FK8rg61fyticaiphplc6wb3o68p FOREIGN KEY("user_id") REFERENCES public."user";

ALTER TABLE
    IF EXISTS topic ADD CONSTRAINT FKjy82itq5pcd3u2f8nvtrms0bn FOREIGN KEY(created_by_id) REFERENCES public."user";
